package wine.cellar.entity;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import lombok.Data;

@Data
@Entity
public class Cellar {
	@Id // This specifies the primary key of my entity
	@GeneratedValue(strategy = GenerationType.IDENTITY) // This annotation indicates that the primary key should be generated by the db automatically upon insertion
	private Long cellarId;
	private String cellarName;
	private String location;
	private String capacity;

	@ManyToOne
	@JoinColumn(name = "owner_id")
	@JsonIgnoreProperties("cellar") // This annotation is used to prevent issues during JSON serialization, I was having recursion issues initially
	private Owner owner;

	@OneToMany(mappedBy = "cellar", cascade = CascadeType.ALL)
	@JsonIgnoreProperties("cellar")
	private List<Wine> wines;
}